server:
  AppVersion: 1.0.0
  Port: :8080
  Mode: Development
  Debug: false
  Address: ""
  Network: "tcp"

httpServer:
  network: "tcp"
  address: "8081"

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

TelegramBotConfig:
  Timeout: 60
  Token: ""

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: postgres
  PostgresqlSslmode: false
  PgDriver: pgx
memcached:
  URL: "memcached:11211"
  Expiration: 3600