server:
  AppVersion: 1.0.0
  Port: :8080
  Mode: Development
  ReadTimeout: 5
  WriteTimeout: 5
  Debug: false
  Address: ""
  Network: "tcp"

httpServer:
  network: "tcp"
  address: "8081"

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: auth_db
  PostgresqlSslmode: false
  PgDriver: pgx
memcached:
  URL: ""
  Expiration: 3600